[workspace]
members = [
    "embedded-storage",
    "embedded-storage-async"
]
resolver = "3"

package.edition = "2024"
package.rust-version = "1.87"
package.description = "A Storage Abstraction Layer for Embedded Systems"
package.license = "MIT OR Apache-2.0"
package.repository = "https://github.com/rust-embedded-community/embedded-storage"
