on:
  push:
    branches: [master]
  pull_request:

name: Continuous integration

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All generated code should be running on stable and msrv
        rust: ["1.87", stable]

        # The default target we're compiling on and for
        TARGET: [x86_64-unknown-linux-gnu, thumbv6m-none-eabi]

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.TARGET }}
      - run: cargo check --target ${{ matrix.TARGET }}
